//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills
    {
        public int id { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
