//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoАnalyser
    {
        public int id { get; set; }
        public Nullable<System.DateTime> data_receipt { get; set; }
        public Nullable<System.TimeSpan> date_completion { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_analyser { get; set; }
        public Nullable<int> id_servicesfororder { get; set; }
    
        public virtual Analyser Analyser { get; set; }
        public virtual ServicesForOrder ServicesForOrder { get; set; }
        public virtual Users Users { get; set; }
    }
}
