//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesForOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServicesForOrder()
        {
            this.InfoАnalyser = new HashSet<InfoАnalyser>();
        }
    
        public int id { get; set; }
        public int id_order { get; set; }
        public int id_service { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> tube_code { get; set; }
        public string result { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoАnalyser> InfoАnalyser { get; set; }
        public virtual Order Order { get; set; }
        public virtual Services Services { get; set; }
        public virtual Status Status { get; set; }
    }
}
