//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users_()
        {
            this.Bills_ = new HashSet<Bills_>();
            this.HistoryIn_ = new HashSet<HistoryIn_>();
            this.Info_analyser_ = new HashSet<Info_analyser_>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<int> id_type { get; set; }
        public Nullable<int> id_role { get; set; }
        public Nullable<int> id_insurance { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<double> number_polis { get; set; }
        public Nullable<double> pasport { get; set; }
        public Nullable<double> phone_number { get; set; }
        public string email { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bills_> Bills_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryIn_> HistoryIn_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Info_analyser_> Info_analyser_ { get; set; }
        public virtual insurance_ insurance_ { get; set; }
        public virtual Role_ Role_ { get; set; }
        public virtual TypesPolises_ TypesPolises_ { get; set; }
    }
}
