//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Bills = new HashSet<Bills>();
            this.HistoryIn = new HashSet<HistoryIn>();
            this.InfoАnalyser = new HashSet<InfoАnalyser>();
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<int> id_type { get; set; }
        public Nullable<int> id_role { get; set; }
        public Nullable<int> id_insurance { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string number_polis { get; set; }
        public Nullable<double> pasport { get; set; }
        public Nullable<double> phone_number { get; set; }
        public string email { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bills> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryIn> HistoryIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoАnalyser> InfoАnalyser { get; set; }
        public virtual Insurance Insurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Role Role { get; set; }
        public virtual TypesPolises TypesPolises { get; set; }
    }
}
